# scale-config.yml:
#   Powers what instance types are available for GHA auto-scaled
#   runners. Runners listed here will be available as self hosted
#   runners, configuration is directly pulled from the main branch.
#

runner_types:
  windows.4xlarge:
    instance_type: c5d.4xlarge
    os: windows
    max_available: 20
    disk_size: 256
