# Site settings
title: "PyTorch Website"
author: "Shift Lab"
description: "Static website for pytorch.org"
url: "https://shiftlab.github.io"
default_author: The PyTorch Team
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
sass:
  load_paths:
    - _sass
    - node_modules
exclude: [vendor, node_modules]
github: [metadata]
baseurl: "/pytorch"
external_urls:
  github: https://github.com/pytorch/pytorch
  github_issues: https://github.com/pytorch/pytorch/issues
  contributing: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md
  docs: https://pytorch.org/docs/stable/index.html
  twitter: https://twitter.com/pytorch
  facebook: https://www.facebook.com/pytorch
  slack: https://pytorch.slack.com
  discuss: https://discuss.pytorch.org
livereload: true
markdown: kramdown
highlighter: rouge
collections:
  tutorials:
    output: false
  ecosystem:
    output: true
    permalink: /ecosystem/:path/
  style_guide:
    output: false
  posts:
    output: true
    permalink: /blog/:title/

pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2