# Site settings
title: "PyTorch Website"
author: "Shift Lab"
description: "Static website for pytorch.org"
url: "https://shiftlab.github.io"
sass:
  load_paths:
    - _sass
    - node_modules
exclude: [vendor, node_modules]
github: [metadata]
baseurl: "/pytorch"
livereload: true
markdown: kramdown
highlighter: rouge
collections:
  - tutorials
