version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    branches:
      only:
        - master
    steps:
      - checkout

      - restore_cache:
          keys:
            - pytorch-bundle-v2-{{ checksum "Gemfile.lock" }}
            - pytorch-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle

      - save_cache:
          key: pytorch-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - pytorch-yarn-{{ checksum "yarn.lock" }}
            - pytorch-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: pytorch-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build Jekyll site and push to gh-pages
          command: ./scripts/deploy-ghpages.sh build
