name: Check quick-start-module.js regen
on:
  push:
    branches:
      - site
  pull_request:

jobs:
  check-regen:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout Pytorch.github.io
        uses: actions/checkout@v2
      - name: Regen quick-start-module
        run: |
          python3 scripts/gen_quick_start_module.js >assets/quick-start-module.js
          CHANGES=$(git status --porcelain "assets/quick-start-module.js")
          echo "$CHANGES"
          [ -z "$CHANGES" ]

